// var summaryfilter={
// 	source:[],
// 	level:"",
// 	question:"",
// 	publication:"",
// 	species:"",
// 	subject:"",
// 	age:""
// }

// var detailfilter={
// 	source:[],
// 	level:"",
// 	publication:"",
// 	species:"",
// 	subject:"",
// 	age:""
// }


var summary=[
	{
		Article:"Article1",
		Publishdate:"Date1",
		Author:"Author1",
		Link:"Link1"
	},
	{
		Article:"Article2",
		Publishdate:"Date2",
		Author:"Author2",
		Link:"Link2"
	},
	{
		Article:"Article3",
		Publishdate:"Date3",
		Author:"Author3",
		Link:"Link3"
	},
	{
		Article:"Article4",
		Publishdate:"Date4",
		Author:"Author4",
		Link:"Link4"
	},
	{
		Article:"Article5",
		Publishdate:"Date5",
		Author:"Author5",
		Link:"Link5"
	},
	{
		Article:"Article6",
		Publishdate:"Date6",
		Author:"Author6",
		Link:"Link6"
	},
	{
		Article:"Article1",
		Publishdate:"Date1",
		Author:"Author1",
		Link:"Link1"
	},
	{
		Article:"Article2",
		Publishdate:"Date2",
		Author:"Author2",
		Link:"Link2"
	},
	{
		Article:"Article3",
		Publishdate:"Date3",
		Author:"Author3",
		Link:"Link3"
	},
	{
		Article:"Article4",
		Publishdate:"Date4",
		Author:"Author4",
		Link:"Link4"
	},
	{
		Article:"Article5",
		Publishdate:"Date5",
		Author:"Author5",
		Link:"Link5"
	},
	{
		Article:"Article6",
		Publishdate:"Date6",
		Author:"Author6",
		Link:"Link6"
	},
	{
		Article:"Article1",
		Publishdate:"Date1",
		Author:"Author1",
		Link:"Link1"
	},
	{
		Article:"Article2",
		Publishdate:"Date2",
		Author:"Author2",
		Link:"Link2"
	},
	{
		Article:"Article3",
		Publishdate:"Date3",
		Author:"Author3",
		Link:"Link3"
	},
	{
		Article:"Article4",
		Publishdate:"Date4",
		Author:"Author4",
		Link:"Link4"
	},
	{
		Article:"Article5",
		Publishdate:"Date5",
		Author:"Author5",
		Link:"Link5"
	},
	{
		Article:"Article6",
		Publishdate:"Date6",
		Author:"Author6",
		Link:"Link6"
	},
	{
		Article:"Article1",
		Publishdate:"Date1",
		Author:"Author1",
		Link:"Link1"
	},
	{
		Article:"Article2",
		Publishdate:"Date2",
		Author:"Author2",
		Link:"Link2"
	},
	{
		Article:"Article3",
		Publishdate:"Date3",
		Author:"Author3",
		Link:"Link3"
	},
	{
		Article:"Article4",
		Publishdate:"Date4",
		Author:"Author4",
		Link:"Link4"
	},
	{
		Article:"Article5",
		Publishdate:"Date5",
		Author:"Author5",
		Link:"Link5"
	},
	{
		Article:"Article6",
		Publishdate:"Date6",
		Author:"Author6",
		Link:"Link6"
	}

]

var detail=[
	{
		Evidence:"evidence1(id1)",
		Source:"source1",
		Quantity:"quantity1",
		Article:"Article1"
	},
	{
		Evidence:"evidence2(id2)",
		Source:"source2",
		Quantity:"quantity2",
		Article:"Article2"
	},
	{
		Evidence:"evidence3(id3)",
		Source:"source3",
		Quantity:"quantity3",
		Article:"Article3"
	},
	{
		Evidence:"evidence4(id4)",
		Source:"source4",
		Quantity:"quantity4",
		Article:"Article4"
	},
	{
		Evidence:"evidence5(id5)",
		Source:"source5",
		Quantity:"quantity5",
		Article:"Article5"
	},
	{
		Evidence:"evidence6(id6)",
		Source:"source6",
		Quantity:"quantity6",
		Article:"Article6"
	},
	{
		Evidence:"evidence1(id1)",
		Source:"source1",
		Quantity:"quantity1",
		Article:"Article1"
	},
	{
		Evidence:"evidence2(id2)",
		Source:"source2",
		Quantity:"quantity2",
		Article:"Article2"
	},
	{
		Evidence:"evidence3(id3)",
		Source:"source3",
		Quantity:"quantity3",
		Article:"Article3"
	},
	{
		Evidence:"evidence4(id4)",
		Source:"source4",
		Quantity:"quantity4",
		Article:"Article4"
	},
	{
		Evidence:"evidence5(id5)",
		Source:"source5",
		Quantity:"quantity5",
		Article:"Article5"
	},
	{
		Evidence:"evidence6(id6)",
		Source:"source6",
		Quantity:"quantity6",
		Article:"Article6"
	},
	{
		Evidence:"evidence1(id1)",
		Source:"source1",
		Quantity:"quantity1",
		Article:"Article1"
	},
	{
		Evidence:"evidence2(id2)",
		Source:"source2",
		Quantity:"quantity2",
		Article:"Article2"
	},
	{
		Evidence:"evidence3(id3)",
		Source:"source3",
		Quantity:"quantity3",
		Article:"Article3"
	},
	{
		Evidence:"evidence4(id4)",
		Source:"source4",
		Quantity:"quantity4",
		Article:"Article4"
	},
	{
		Evidence:"evidence5(id5)",
		Source:"source5",
		Quantity:"quantity5",
		Article:"Article5"
	},
	{
		Evidence:"evidence6(id6)",
		Source:"source6",
		Quantity:"quantity6",
		Article:"Article6"
	}
]

var summarypage={
	current:1,
	total:1,
	shownum:8
}

var detailpage={
	current:1,
	total:1,
	shownum:8
}